# Generated by Django 4.0.1 on 2023-06-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('calorie', models.CharField(max_length=20)),
                ('carbohydrates', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('fat', models.CharField(max_length=20)),
                ('sugar', models.CharField(max_length=20)),
                ('sodium', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sprintapp_fooddata',
            },
        ),
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('calorie', models.CharField(max_length=20)),
                ('carbohydrates', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('fat', models.CharField(max_length=20)),
                ('sugar', models.CharField(max_length=20)),
                ('sodium', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sprintapp_nutritiondata',
            },
        ),
    ]
