# Generated by Django 4.0.1 on 2023-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('unique_id', models.IntegerField()),
            ],
        ),
    ]
